### ISSUE TITLE
subtitlecomposer 0.6.0

### ISSUE THREAD

**Issue by maxrd2** [Martchus/PKGBUILDs#1]
Version 0.6.0 is tagged.
Please check updated [PKGBUILD](https://github.com/maxrd2/subtitlecomposer/blob/master/pkg/arch/PKGBUILD)
    
    Added cmake params in build() needed for correct plugin installation:
        -DLIB_INSTALL_DIR=lib
        -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
    
    Added cmake params in build() to skip building of tests:
        -DBUILD_TESTING=OFF
    
    Added some make/optdepens since these are external .so now and not linked against binary:
        'mpv: for MPV backend'
        'mplayer: for MPlayer backend'
        'xine-lib: for Xine backend'

**Comment by Martchus** [comment]
Updated the PKGBUILD. The pluggable media player backends seem to work correctly. Thanks for this improvement.
By the way, I've noticed that the German translation is still full of gaps. I'll try to improve it when I have time.

**Comment by maxrd2** [comment]
Thanks, please add your self to contributors in (README.md, main.cpp)
Have already added you to readme, but am not sure if you want to use your real name.

Have already tagged 0.6.1 as I have found some ugly bug with anchor points. Was a bit hasty with tagging 0.6.0 without proper testing.
