### ISSUE TITLE
cross-compile angle with samples

### ISSUE THREAD

**Issue by tomilov** [Martchus/PKGBUILDs#10]
Is it possible to build angle with samples? Didn't see samples in `out/` directory and can't understand how to fix this.

**Comment by Martchus** [comment]
I can try.

**Comment by tomilov** [comment]
`gyp -D angle_build_winrt=0` does not work.

**Comment by Martchus** [comment]
Doesn't work doesn't help me, but I will have to test myself anyways.

This is what I've got so far: https://github.com/Martchus/PKGBUILDs/tree/angleproject
But I still have to test.

**Comment by tomilov** [comment]
I told about that. I looked through this project but I can't make tests and samples, though https://github.com/google/angle/blob/f097e2380650696a4c20624e4668a184980e4d7d/build/ANGLE.gyp#L23 is present in the configuration (revision is exactly mentioned in `angleproject/mingw-w64/PKGBUILD`).

**Comment by Martchus** [comment]
Commit https://github.com/Martchus/PKGBUILDs/commit/b2c33b6411aff5a8fae9d719170daca05d15f46d should do it.

At least I was able to build it (https://martchus.no-ip.biz/repo/arch/ownstuff/os/x86_64). Haven't tested whether it actually works yet.

Samples are in split package. I put assets for samples under `share/angleproject/samples` so `bin` remains clean. Not sure how to tell ANGLE location of assets, though.

> `gyp -D angle_build_winrt=0` does not work.

I can just say that the build system ANGLE is horrible (so don't expect anything to work that easily).

> There is `build/gyp_angle` wrapper for `gyp` utility, which is not used as intended. Maybe is problem here?

This did never work for me.

**Comment by tomilov** [comment]
Great work. Thank you. How to obtain such a skill?

**Comment by Martchus** [comment]
Ok, then I'll close this.

> How to obtain such a skill?

I just maintain this (and other packages) quite a while now and hence gained a little experience in finding hacky workarounds in build systems to make cross compilation work. Often, like in case of ANGLE, cross compilation or compilation with mingw-w64 in general is not officially supported so it is actually quite normal to find such issues. Sometimes it is also useful to just contact the developers, eg. some dev in #ANGLEproject channel on IRC told me how to enable the static build (and that it is not officially supported).
