### ISSUE TITLE
[request] add AUR packages to ownstuff (binary)

### ISSUE THREAD

**Issue by hhromic** [Martchus/PKGBUILDs#100]
Hello!
Would it be possible to add the following AUR packages to your ownstuff binary repository?

    mingw-w64-sdl2_image
    mingw-w64-sdl2_ttf
    mingw-w64-physfs
    mingw-w64-luajit-2.1

The first two are very common SDL2 submodules for image and truetype fonts usage in SDL2.

The `physfs` library is a very nice library to provide abstract access to various archives (for example compressed) without uncompressing them, like a VFS. It is used in various open source games.

Lastly, `luajit` is drop-in JIT replacement of the Lua scripting language engine. It is faster than plain Lua and also is used in various applications and games that support scripting.

These packages should be very small in binary form, I hope you are okay with adding them!

**Comment by Martchus** [comment]
Ok, why not - these libs were quite small and fast to build anyways :-)

I also added the regular `luajit-2.1`.

**Comment by hhromic** [comment]
Thanks a lot for that!
Your binary repo saves me a lot of building time and hassle!
Really appreciate your work :)

**Comment by hhromic** [comment]
Hi @Martchus,

Some days ago I submitted a patch to the `mingw-w64-luajit-2.1` package in the AUR [1] that makes it compatible with CMake 3.17. I remember that you mentioned once that you have an automated process that re-builds packages from the AUR that you track in your repository, however I haven't seen the updated version of the package yet.

I'm wondering if your automated process is down or something else happened to it?
There is no rush from my side though, mostly asking just in case :)

Thanks again for all your work in this repo, it is really useful :+1: 

[1] https://aur.archlinux.org/packages/mingw-w64-luajit-2.1/

**Comment by Martchus** [comment]
I was recently busy with https://github.com/Martchus/PKGBUILDs/issues/56 so I haven't done any actual updates. I'll continue updating but I also need to sort out some things with my new build system. It is still "only" a semi-automated process.

**Comment by hhromic** [comment]
Oh apologies, I thought you had it fully automated!
I saw now that the package is updated in your repo :) Thanks for your time, appreciated!
Good luck with your new build system, hope you can bring it closer to fully automated :)

**Comment by Martchus** [comment]
Me, too. The build system should help me to detect automatically which packages need to be rebuilt when it is completed. Then it would make sense to automate it fully.
