### ISSUE TITLE
[pistache-git] No static files found when build a c++ project using pistache

### ISSUE THREAD

**Issue by NeodarZ** [Martchus/PKGBUILDs#101]
Hello,

I make a project where I use pistache, and so your PKGBUILD. But I have a problem when I run cmake:

```
CMake Error at /usr/lib64/cmake/pistache/PistacheTargets.cmake:83 (message):
  The imported target "pistache_static" references the file
     "/usr/lib64/libpistache.a"
  but this file does not exist.  Possible reasons include:
  * The file was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and contained
     "/usr/lib64/cmake/pistache/PistacheTargets.cmake"
  but not all the files it references.
Call Stack (most recent call first):
  /usr/lib64/cmake/pistache/PistacheConfig.cmake:43 (include)
  CMakeLists.txt:9 (find_package)
```

In my CMakeLists.txt file I didn't use pistache static library (like you can see here:
https://git.neodarz.net/pro/umosapicpp.git/tree/CMakeLists.txt).

I can build my code only if I add an option to the PKGBUILD to leave the static
library files. I think it's a better idea if you add this option in the
PKGBUILD, what do you think?

And thanks for your work

**Comment by Martchus** [comment]
That would make sense. Especially since the library likely doesn't offer a stabile ABI it makes even sense to use the static target. If you like you can just go ahead and open a PR.

**Comment by Martchus** [comment]
Should be fixed now
