### ISSUE TITLE
Static builds with FORTIFY_SOURCE fail

### ISSUE THREAD

**Issue by ypnos** [Martchus/PKGBUILDs#107]
I found that since recently, static builds fail. For example, I suddenly cannot build aur/mingw-w64-intel-tbb anymore.

I found this thread that gives good background information: https://github.com/msys2/MINGW-packages/issues/5803

I also found that when I try to build my own project, it helps to change the C and CXX flag from `-D_FORTIFY_SOURCE=0` to `-D_FORTIFY_SOURCE=2` with my own stuff. But I get stuck with these:

```
/usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libpcre2-16.a(libpcre2_16_la-pcre2_compile.o):(.text+0x5c61): undefined reference to `__memcpy_chk'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libQt5FontDatabaseSupport.a(qwindowsfontdatabase.o):(.text+0x15b1): undefined reference to `__memcpy_chk'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libQt5FontDatabaseSupport.a(qwindowsfontdatabase.o):(.text+0x3044): undefined reference to `__memcpy_chk'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libQt5FontDatabaseSupport.a(qwindowsfontdatabase.o):(.text+0x3b1f): undefined reference to `__memcpy_chk'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libQt5FontDatabaseSupport.a(qwindowsfontdatabase.o):(.text+0x4764): undefined reference to `__memcpy_chk'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libQt5FontDatabaseSupport.a(qwindowsfontdatabase.o):(.text+0x92b1): more undefined references to `__memcpy_chk' follow
```

Do you also see this problem?

**Comment by Martchus** [comment]
I have released the static builds for my project Syncthing Tray yesterday. So it generally works. I have seen this error before but it should be fixed within current versions of `mingw-w64-configure`/`mingw-w64-cmake`/`mingw-w64-qt5-base`.

**Comment by ypnos** [comment]
Adding `-fstack-protector` indeed solves the problem. Thanks!

Great that there is no need to rebuild dependencies. However I thought my packages are most recent. Are they not?
```
local/mingw-w64-configure 0.1.1-9
local/mingw-w64-cmake 1-33
```

**Comment by Martchus** [comment]
These are recent. Not sure why the flag isn't present on the linker line, then.

For qmake, note that I've pushed mingw-w64-qt5-base 5.13.2-**2**.

**Comment by ypnos** [comment]
Yes I have that version as well. And with a fresh CMake cache it also works as expected.

Thanks again!
