### ISSUE TITLE
[request] add mingw-w64-lua51 AUR package to ownstuff (binary)

### ISSUE THREAD

**Issue by hhromic** [Martchus/PKGBUILDs#108]
Hello and happy new year!
This is a similar request as in #100.

Would it be possible to add the following AUR package to your ownstuff binary repository?

    mingw-w64-lua51

As you probably know Lua is a very popular scripting language and is used in various applications and games that support scripting. Your repository already has `mingw-w64-lua` which is the 5.3 version of Lua, however the 5.1 version is also very wide-spread.

The package should be very small in binary form, I hope you are okay with adding it.

**Comment by Martchus** [comment]
I added it. Lua is quite lightweight so that's not a big deal.

**Comment by hhromic** [comment]
Thanks! Appreciated! :)
