### ISSUE TITLE
error: failed retrieving file 'ownstuff.db' from ftp.f3l.de 403

### ISSUE THREAD

**Issue by xantares** [Martchus/PKGBUILDs#110]
hello,
it seems I have a problem doing pacman -Sy with the ftp.f3l.de mirror since few days, no-ip.biz is fine though
it's weird because I can still read https://ftp.f3l.de/~martchus/ownstuff/os/ with my browser

**Comment by Martchus** [comment]
That's weird indeed. Maybe there were some downtimes because @asdil12 is migrating the server? What error message do you get exactly from pacman?

**Comment by asdil12** [comment]
Seems that the `ownstuff.db` symlink didn't get copied to the new server.

**Comment by Martchus** [comment]
The permissions for symlinks weren't set correctly in the Apache config. It should be fixed now.

**Comment by xantares** [comment]
thanks, everything is fine now
