### ISSUE TITLE
Sphinxbase doxy2swig issue

### ISSUE THREAD

**Issue by dvs999** [Martchus/PKGBUILDs#118]
Hi, There seems to be an issue building the sphinxbase package? Attached is a patchfile to apply the fix from the Fedora Core 32 sphinxbase SRPM. 
[sphinxbase-doxy2swig.zip](https://github.com/Martchus/PKGBUILDs/files/4616266/sphinxbase-doxy2swig.zip)

**Comment by Martchus** [comment]
Can you create a PR? This would make it easier for me. And is it really required to apply the patch after configure? Otherwise, please move it to the prepare function.

**Comment by dvs999** [comment]
Apologies. First time I tried it in the Prepare section it didn't seem to work but I think I must have had a lingering src directory. Sorted now. Will sort a PR shortly
