### ISSUE TITLE
mingw-w64-p11-kit needs libffi-6.dll but mingw-w64-libffi provides libffi-7.dll

### ISSUE THREAD

**Issue by dubhater** [Martchus/PKGBUILDs#121]
Hello!

I just installed mingw-w64-p11-kit 0.23.20-1.1 and mingw-w64-libffi 3.3-1 and got an error message because there is no libffi-6.dll.

Thank you for making these binary packages. They are very convenient.

**Comment by Martchus** [comment]
Seems like I've forgotten a rebuild. Thanks for letting me know. I'll check which packages are affected and try to rebuild them.

**Comment by Martchus** [comment]
Only `mingw-w64-p11-kit` was affected and has been rebuilt.

**Comment by dubhater** [comment]
Thank you! It works now.
