### ISSUE TITLE
Pocketsphinx 3.7 issue

### ISSUE THREAD

**Issue by yamimax** [Martchus/PKGBUILDs#122]
Hi, Is there any binary file or any way I can pocketsphinx in python 3.7.
I am really struggling to get it installed

**Comment by Martchus** [comment]
Arch Linux only provides Python 3.8 and Python 2.7 at this time. Hence these Python versions are used to build `sphinxbase` and `pocketsphinx`. If you really wanted to use Python 3.7 you could create a `python37` package (similarly to Lua packaging where we currently have `lua52` in the official repos) and make packages `sphinxbase37`/`pocketsphinx37` which would depend on this package. I suppose a `python37` might already exist within the AUR.

**Comment by Martchus** [comment]
By the way, I suppose that's how one would package it. But what's the point of packaging this for an old Python version in the first place? When I remember correctly, there's actually tooling available in the Python eco system which would allow installing dependencies for various Python versions. (Maybe there's a limitation within that tooling when it comes to libraries containing native code?)

**Comment by Martchus** [comment]
I'm closing because I've got no response and otherwise there seems nothing for me to do here.
