### ISSUE TITLE
Checksum error in syncthingtray PKGBUILD 1.1.3

### ISSUE THREAD

**Issue by iRaphis** [Martchus/PKGBUILDs#130]
Dear Martchus,
thanks for taking care of this neat little tool. I tried upgrading today in Manjaro but it gives me build errors because of the checksum:

> Erstelle syncthingtray...
> ==> Erstelle Paket: syncthingtray 1.1.3-1 (Sa 06 Mär 2021 19:54:47 CET)
> ==> Prüfe Laufzeit-Abhängigkeiten...
> ==> Prüfe Buildtime-Abhängigkeiten...
> ==> Empfange Quellen...
>   -> Lade syncthingtray-1.1.3.tar.gz herunter...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100   130  100   130    0     0   2166      0 --:--:-- --:--:-- --:--:--  2166
> 
> 100 1517k    0 1517k    0     0  3675k      0 --:--:-- --:--:-- --:--:-- 3675k
> ==> Überprüfe source Dateien mit sha256sums...
>     syncthingtray-1.1.3.tar.gz ... FEHLGESCHLAGEN
> ==> FEHLER: Eine oder mehrere Dateien überstanden nicht die Gültigkeits-Prüfung!
> Fehler beim Erstellen von syncthingtray

If I download from
https://github.com/Martchus/syncthingtray/archive/v1.1.3.tar.gz
the files has the SHA256 checksum of
7e6580e8dee78fb3a3dacf4d55f02c7f8b44dac1785275bb7d937e59f57f295b

Of course if I modify the PKGBUILD locally it installs fine.

Regards, Raphael

**Comment by Martchus** [comment]
Should be fixed by https://github.com/Martchus/PKGBUILDs/commit/b3506546819951166f0e40d2c9a7f9096baf1009
