### ISSUE TITLE
Adding package signatures requires manual intervention

### ISSUE THREAD

**Issue by pingplug** [Martchus/PKGBUILDs#131]
I got an error today:
```
looking for conflicting packages...

Packages (1) mingw-w64-sqlite-3.35.1-1

Total Installed Size:  9.89 MiB
Net Upgrade Size:      0.11 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                     [----------------------] 100%
(1/1) checking package integrity                   [----------------------] 100%
error: mingw-w64-sqlite: signature from "Martchus <martchus@gmx.net>" is unknown trust
:: File /var/cache/pacman/pkg/mingw-w64-sqlite-3.35.1-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
```

in `/etc/pacman.conf`:
```
[ownstuff]
Server = https://ftp.f3l.de/~martchus/$repo/os/$arch
Server = https://martchus.no-ip.biz/repo/arch/$repo/os/$arch
SigLevel = PackageOptional
```

**Comment by Martchus** [comment]
I've started to sign packages. This means you either need to trust the key (1) or set `SigLevel = Optional TrustAll` (2).

Of course (1) would be the preferred solution to actually benefit from the signatures. How to add unofficial keys is documented in the [Wiki](https://wiki.archlinux.org/index.php/Pacman/Package_signing#Adding_unofficial_keys). I've also been adding concrete example commands for my repository to the setup instructions found within its [directory listing](https://martchus.no-ip.biz/repo/arch/ownstuff/os/x86_64). I've also update the repository's section on the [Unofficial user repositories](https://wiki.archlinux.org/index.php/Unofficial_user_repositories#ownstuff) Wiki page.

**Comment by lquessenberry** [comment]
I'm here learning Manjaro, Arch, and SteamOS simultaneously. Thanks for your help. I have been searching for a way to build libxcrypt-compat to satisfy a few dependencies. Bookmarking this for other SteamDeck power users
