### ISSUE TITLE
error: key "E06FE8F53CDC6A4C" could not be looked up remotely

### ISSUE THREAD

**Issue by xDShot** [Martchus/PKGBUILDs#133]

**Comment by xDShot** [comment]
$ sudo pacman-key --recv-keys B9E36A7275FC61B464B67907E06FE8F53CDC6A4C # import key
gpg: keyserver receive failed: No keyserver available
==> ERROR: Remote key not fetched correctly from keyserver.

**Comment by xDShot** [comment]
--keyserver keyserver.ubuntu.com appears working. Do you know default keyserver it tries to pull from?

**Comment by Martchus** [comment]
It uses the server you've configured within `/etc/pacman.d/gnupg/gpg.conf`.

**Comment by xDShot** [comment]
Thanks. Closing as it's on my end.
