### ISSUE TITLE
[syncthingtray] yay -Yc keep deleting syncthing

### ISSUE THREAD

**Issue by AchmadFathoni** [Martchus/PKGBUILDs#142]
syncthingtray PKGBUILD declares syncthing only as **checkdepends**
https://github.com/Martchus/PKGBUILDs/blob/8a71ef2410582810528ccc0f058e27eaebe0e709/syncthingtray/default/PKGBUILD#L41
This makes `yay -Yc` deletes syncthing because it thinks syncthingtray doesn't depend on syncthing at runtime. How about move syncthing as **depends**?

**Comment by Martchus** [comment]
Syncthing Tray doesn't strictly depend on Syncthing. You can also use it to connect to a remote instance or a use a custom Syncthing binary as paths can be easily configured in the UI.

I don't use `yay` and this is not `yay`'s issue tracker so I cannot tell you anything about it. However, it seems generally unreasonable to uninstall the `syncthing` package from the system if it was installed before the build. I personally recommend to build packages via `makechrootpkg` like the official Arch Linux devs do. This avoids builds from tampering with your normal system altogether.

**Comment by Martchus** [comment]
Btw, I suppose `yay` would have uninstalled a previously installed `iproute2` and `cppunit` package as well if no other package would have depended on it. But you're not asking me to add these two packages to the normal depends as well, right? If that was the case we'd scrap `checkdepends` altogether in favor of just using `depends` and that's clearly not how it is supposed to be done.

**Comment by AchmadFathoni** [comment]
Yeah you right, I should use `yay -S syncthing --asexplicit` instead.

**Comment by Martchus** [comment]
Ah, if the package hasn't been explicitly installed the behavior of `yay` makes more sense. So yes, just do that. (I guess that's what pacman does by default if you'd use `pacman -Sy syncthing` so I haven't considered that `syncthing` might not be explicitly installed.)
