### ISSUE TITLE
Could you add mingw-w64-gdb to [ownstuff]

### ISSUE THREAD

**Issue by yan12125** [Martchus/PKGBUILDs#150]
Hi, thanks a lot for maintaining this repo! I cross-build programs for Windows and as well as use Windows programs under wine from time to time, and I find mingw-w64 packages very useful. Could you consider adding https://aur.archlinux.org/packages/mingw-w64-gdb to help debugging? It needs several AUR dependencies, and all of them are already in [ownstuff]:

* mingw-w64-dlfcn
* mingw-w64-expat
* mingw-w64-mpfr
* mingw-w64-readline
* mingw-w64-zlib
* mingw-w64-configure

Also, this package builds fine in chroots with [ownstuff] repo without modifying PKGBUILD.

**Comment by Martchus** [comment]
I'll add it after concluding the OpenSSL 3 rebuild.

**Comment by yan12125** [comment]
Awesome, thanks!
