### ISSUE TITLE
subtitlecomposer: Error validating checksum & video fix

### ISSUE THREAD

**Issue by oyale** [Martchus/PKGBUILDs#151]
Commit patch checksum is failing [(here)](https://github.com/Martchus/PKGBUILDs/blob/07c33b3d7e644a05dd8e1f47463b2b0e0c4c6d7f/subtitlecomposer/default/PKGBUILD#LL34C12-L34C12)

Also, the bug causing video loading to fail is fixed as indicated by [this mail](https://www.mail-archive.com/kde-bugs-dist@kde.org/msg700354.html), so we should also load the commit patch d8f9797d8f979797.

I will open a PR with these two fixes :)

Thanks for your work in bringing all these packages to AUR!

**Comment by Martchus** [comment]
Merged the PR. It'll be rebuilt later (currently there are still other builds in the queue).

**Comment by oyale** [comment]
I'm sorry, but I've created another PR https://github.com/Martchus/PKGBUILDs/pull/153: the URL for the commit patch was missing.

**Comment by Martchus** [comment]
Note that the patch must have really changed. I still had the old version locally and that's the diff (of the diff):

```
$ diff -Naur 4f4f560e40ba0b760cf688eb024be3cc734ca347.patch{,.bak}
--- 4f4f560e40ba0b760cf688eb024be3cc734ca347.patch      2022-11-21 16:14:28.182877379 +0100
+++ 4f4f560e40ba0b760cf688eb024be3cc734ca347.patch.bak  2022-04-17 01:10:44.372306904 +0200
@@ -11,7 +11,7 @@
  4 files changed, 4 insertions(+), 2 deletions(-)
 
 diff --git a/src/streamprocessor/streamprocessor.cpp b/src/streamprocessor/streamprocessor.cpp
-index b86795e7..8faf8a29 100644
+index b86795e..8faf8a2 100644
 --- a/src/streamprocessor/streamprocessor.cpp
 +++ b/src/streamprocessor/streamprocessor.cpp
 @@ -195,7 +195,7 @@ StreamProcessor::findStream(int streamType, int streamIndex, bool imageSub)
@@ -24,7 +24,7 @@
                        qWarning() << "Failed to find decoder for stream" << i;
                        return false;
 diff --git a/src/videoplayer/backend/decoder.h b/src/videoplayer/backend/decoder.h
-index 4ab95b2c..fb6840de 100644
+index 4ab95b2..fb6840d 100644
 --- a/src/videoplayer/backend/decoder.h
 +++ b/src/videoplayer/backend/decoder.h
 @@ -11,6 +11,7 @@
@@ -36,7 +36,7 @@
  }
  
 diff --git a/src/videoplayer/backend/framequeue.h b/src/videoplayer/backend/framequeue.h
-index dc9b2fa4..ece11668 100644
+index dc9b2fa..ece1166 100644
 --- a/src/videoplayer/backend/framequeue.h
 +++ b/src/videoplayer/backend/framequeue.h
 @@ -9,6 +9,7 @@
@@ -48,7 +48,7 @@
  }
  
 diff --git a/src/videoplayer/backend/streamdemuxer.cpp b/src/videoplayer/backend/streamdemuxer.cpp
-index 1e339b33..e8320ea0 100644
+index 1e339b3..e8320ea 100644
 --- a/src/videoplayer/backend/streamdemuxer.cpp
 +++ b/src/videoplayer/backend/streamdemuxer.cpp
 @@ -230,7 +230,7 @@ StreamDemuxer::componentOpen(int streamIndex)
```

**Comment by oyale** [comment]
I'm not sure if I'm understanding the diff (of the diff).  Is there any change beyond the commit ref being a shorter char?

**Comment by Martchus** [comment]
Yes, only the commit ref is shorter. Maybe a GitLab update changed that. Considering that, it is maybe not the best idea to reference patches this way after all. (On GitHub I've never experienced any changes when using such URLs but GitLab seems different. For now I'd just keep it this way nevertheless. They likely won't change the format all the times.)

**Comment by Martchus** [comment]
My own builds have passed now as well. I suppose the issue can be closed now.
