### ISSUE TITLE
Please add proper provides to syncthingtray dependencies

### ISSUE THREAD

**Issue by xeruf** [Martchus/PKGBUILDs#156]
For example, `libqtforkawesome-git` should also provide `libqtforkawesome.so`.
And does `syncthingtray-git` really need to depend on the other `-git` versions? If yes, can we somehow fix dependency resolution for AUR helpers so I don't have to manage them manually?

**Comment by Martchus** [comment]
> For example, libqtforkawesome-git should also provide libqtforkawesome.so.

It shouldn't because the `-git` version might not be backwards compatible and thus uses a different soname.

> And does syncthingtray-git really need to depend on the other -git versions?

Yes. The non `-git` packages are very often too old.

> If yes, can we somehow fix dependency resolution for AUR helpers so I don't have to manage them manually?

AUR helpers are out of scope for this repository. If your AUR helper doesn't support soname dependencies, file an issue there.

**Comment by xeruf** [comment]
Well, then it should at least provide `libqtforkawesome-git.so`, currently it provides nothing ^^

**Comment by Martchus** [comment]
It should indeed provide at least `libqtforkawesome-git.so`. Looks like the version in the AUR was never updated as my script to do it automatically doesn't  consider qtforkawesome yet. I've just been updating the AUR package.
