### ISSUE TITLE
cmake-format: specify the purpose of every optional dependency

### ISSUE THREAD

**Issue by tocic** [Martchus/PKGBUILDs#165]
Could you please specify/rephrase the purpose of every optional dependency in the `cmake-format`'s PKGBUILD? There are no comments for `python-yaml` and `python-jinja`. And as far as I can understand, _"automatic shell completion"_ means that I can write `cmake-format --du` and autocomplete the command to `cmake-format --dump`, but that doesn't happen for me.

**Comment by Martchus** [comment]
I'm not sure for what these dependencies are *exactly*. I've just found them when browsing the code and it looked like they are only imported conditionally. Feel free to do a better research and add the information. Maybe upstream's documentation has something to day about it.

Automatic shell completion works fine. Did you forget to register the binary, e.g. via `eval "$( register-python-argcomplete cmake-format )"`?
