### ISSUE TITLE
Qt5 plugins do not populate CMake location properties

### ISSUE THREAD

**Issue by haffmans** [Martchus/PKGBUILDs#168]
Relevant packages: mingw-w64-qt5-base

Your modifications to the build environment (e.g. changes in `makepkg.conf`): None

Question/request or brief description of the problem:

The CMake modules of various Qt plugins do not populate some necessary CMake properties, such as the `LOCATION`. The static version of the package does not have this problem. E.g. `/usr/i686-w64-mingw32/lib/cmake/StaticQt5Gui/StaticQt5Gui_QWindowsIntegrationPlugin.cmake` contains this line:

```
    _populate_Gui_plugin_properties_static(${QT_VARIANT_PREFIX}Qt5::Gui ${QT_VARIANT_PREFIX}Qt5::QWindowsIntegrationPlugin QWindowsIntegrationPlugin RELEASE "platforms/libqwindows.a")
```

There's no counterpart in the dynamically linked version of the package. These lines are supposed to be generated by `mkspecs/features/data/cmake/Qt5PluginTarget.cmake.in` in the Qt sources. From what I found, it looks like patch `0020-Pull-dependencies-of-static-libraries-in-CMake-modul.patch` breaks this file. It removes a bunch of code, but leaves this line still inside the first `!!IF !isEmpty(CMAKE_STATIC_TYPE)` clause in the file:

```
    _populate_$${CMAKE_MODULE_NAME}_plugin_properties(Qt5::$$CMAKE_MODULE_NAME Qt5::$$CMAKE_PLUGIN_NAME $$CMAKE_PLUGIN_NAME RELEASE \"$${CMAKE_PLUGIN_LOCATION_RELEASE}\")
```

Moving one `!!ENDIF` line up (from line 27 in the patched file to line 18; see [this version](https://github.com/Martchus/PKGBUILDs/files/12307302/Qt5PluginTarget.cmake.in.txt)) solves the problem.

**Comment by Martchus** [comment]
Ok, I'll try to pickup and test your change when I have time. I didn't know that plugin targets are even useful when using shared libraries. What are you using this for? What is your test case/project?

**Comment by haffmans** [comment]
I have some custom CMake scripts, based on BundleUtilities, to install the plugins along with the application to make a standalone bundle. Right now I have to apply several work-arounds to keep it all working in different environments, mostly falling back to just the hardcoded DLL name with some additional heuristics to get the proper base directory.

Having this fixed might will probably make it more reliable and hopefully allows me to clean up some if not most of that logic.

See [this code](https://git.simply-life.net/simply-life.net/graphicsrulesmaker/-/blob/master/src/graphicsrulesmakerui/CMakeLists.txt) for an example if you're interested - the whole bundling stuff is quite complex in itself, but works stable enough even without windeployqt.

**Comment by Martchus** [comment]
I've checked out your change and it makes totally sense. I even had a code branch for the shared build to populate this but it got never executed because the outer `!!ENDIF` was too late. I'm currently rebuilding the shared and static base packages and will test whether my own project still build against it. Then I'll push the changes. I'll not rebuild all of the modules for now; they'll get rebuild anyways on the next version bump.

**Comment by Martchus** [comment]
By the way, I'm also playing Sims 2 and  use Graphics Rules Maker. Thanks for keeping the tool alive. It looks like you're porting it to Qt 6. I suppose Qt 6 isn't affected by this problem anyways as I refrained from continuing the heavy patching there (see the [README section](https://github.com/Martchus/PKGBUILDs#brief-documentation-about-mingw-w64-qt-packages) for details).

Note that if you ever wanted to contribute more than such a simple change you could simply provide fixup commits that I'll then incorporate into my patchset (see the [README section](https://github.com/Martchus/PKGBUILDs#contributing-to-patches) for details).

(Considering Qt 6 only supports Windows 10 and later and Sims 2 now falls into "retro gaming" where people might also use older setups it makes of course sense to continue Qt 5 builds supporting both in parallel. In my experience it doesn't seem to be a big deal for Qt Widgets apps.)

**Comment by haffmans** [comment]
Thanks for the fixes! I've tried them and can confirm it now works as expected.

On Qt6 the plugin locations indeed also worked as expected already, so no problems there.

(As an aside: I've dropped Qt5 recently for Graphics Rules Maker, at least for the time being. If there's demand for older Windows versions, I might reintroduce support indeed.)
