### ISSUE TITLE
Add mingw-w64-qt6-positioning

### ISSUE THREAD

**Issue by syyyr** [Martchus/PKGBUILDs#171]
Hi, I was wondering if you could add the qt6 positioning module for the mingw-w64 arch to the AUR.

Thanks.

**Comment by Martchus** [comment]
I'll do when I have time. This shouldn't be a big deal.

**Comment by Martchus** [comment]
I've just pushed the PKGBUILDs and also added qt6-location. I haven't built/tested the PKGBUILDs yet but will do that latest on the next update.

**Comment by Martchus** [comment]
I gave it a test. After some small fixes it builds. My binary repository has been updated as well.
