### ISSUE TITLE
Does not build mingw-w64-postgresql from AUR

### ISSUE THREAD

**Issue by Majestio** [Martchus/PKGBUILDs#173]
Hello!

Already which version of mingw-w64-postgresql build from AUR under Linux Manjaro does not complete successfully. At the moment this is the version:
~~~
# Maintainer: Martchus <martchus@gmx.net>
# Contributor: ant32 <antreimer@gmail.com>

pkgname=mingw-w64-postgresql
pkgver=16.1
pkgrel=1
pkgdesc='Sophisticated object-relational DBMS (mingw-w64)'.
~~~

Here is the part of the build log that shows the errors:

~~~
sed -e 's;FILEDESC;"pgoutput - standard logical replication output plugin";' \
    -e 's;VFT_APP;VFT_DLL;' \
    -e 's;_ICO_;;' \
    -e '/_INTERNAL_NAME_/s;_INTERNAL_NAME_;"pgoutput";' \
    -e '/_ORIGINAL_NAME_/s;_ORIGINAL_NAME_;"pgoutput.dll";' \
  /var/tmp/pamac-build-majestio/mingw-w64-postgresql/src/postgresql-16.1/build-i686-w64-mingw32/../src/port/win32ver.rc >win32ver.rc
i686-w64-mingw32-gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -D_FORTIFY_SOURCE=3 -D_GLIBCXX_ASSERTIONS -O2 -pipe -fno-plt -fexceptions --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fcf-protection   -fvisibility=hidden -I../../../../src/include -I/var/tmp/pamac-build-majestio/mingw-w64-postgresql/src/postgresql-16.1/build-i686-w64-mingw32/../src/include -I/usr/i686-w64-mingw32/include -D_FORTIFY_SOURCE=3 -D_GLIBCXX_ASSERTIONS  -I../src/include/port/win32 -I/usr/i686-w64-mingw32/include/libxml2 -I/usr/i686-w64-mingw32/include  "-I/var/tmp/pamac-build-majestio/mingw-w64-postgresql/src/postgresql-16.1/build-i686-w64-mingw32/../src/include/port/win32" -DWIN32_STACK_RLIMIT=4194304  -c -o pgoutput.o /var/tmp/pamac-build-majestio/mingw-w64-postgresql/src/postgresql-16.1/build-i686-w64-mingw32/../src/backend/replication/pgoutput/pgoutput.c
i686-w64-mingw32-windres -i win32ver.rc -o win32ver.o --include-dir=../../../../src/include --include-dir=/var/tmp/pamac-build-majestio/mingw-w64-postgresql/src/postgresql-16.1/build-i686-w64-mingw32/../src/backend/replication/pgoutput
i686-w64-mingw32-gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -D_FORTIFY_SOURCE=3 -D_GLIBCXX_ASSERTIONS -O2 -pipe -fno-plt -fexceptions --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fcf-protection   -fvisibility=hidden  -shared -static-libgcc -o pgoutput.dll  win32ver.o pgoutput.o -L../../../../src/port -L../../../../src/common  -Wl,-O1,--sort-common,--as-needed -fstack-protector  -Wl,--allow-multiple-definition -Wl,--disable-auto-import -L/usr/i686-w64-mingw32/lib  -fvisibility=hidden -L../../../../src/backend -lpostgres -lpgcommon -lpgport -lintl -lxml2 -lssl -lcrypto -lz -lm  -lws2_32 -Wl,--export-all-symbols -Wl,--out-implib=libpgoutput.dll.a
/usr/lib/gcc/i686-w64-mingw32/13.1.0/../../../../i686-w64-mingw32/bin/ld: pgoutput.o:pgoutput.c:(.text+0xaaf): undefined reference to `defGetStreamingMode'
/usr/lib/gcc/i686-w64-mingw32/13.1.0/../../../../i686-w64-mingw32/bin/ld: pgoutput.o:pgoutput.c:(.text+0x1b5d): undefined reference to `addRTEPermissionInfo'
/usr/lib/gcc/i686-w64-mingw32/13.1.0/../../../../i686-w64-mingw32/bin/ld: pgoutput.o:pgoutput.c:(.text+0x1d5c): undefined reference to `lappend_xid'
/usr/lib/gcc/i686-w64-mingw32/13.1.0/../../../../i686-w64-mingw32/bin/ld: pgoutput.o:pgoutput.c:(.text+0x1d8b): undefined reference to `list_member_xid'
~~~

Please find and fix the cause. Very important library.
Thank you in advance.

**Comment by Martchus** [comment]
It built fine for me. I guess I was still using an older GCC version back then. However, the errors you're getting don't look like that's making a difference here.

I'll have a look when I find the time. If this library is important to you then I recommend having a look at the problem yourself in the meantime. Maybe it is also an issue that needs to be fixed upstream.

Note that Manjaro is generally not supported (although it is unlikely going to make a difference here).

**Comment by Majestio** [comment]
Hello! Yes, something seems to be related to Linux Manjaro. It's just not clear what it is. Just now I specifically installed ArchLinux, built 'yay' and 'pamac', plugged in AUR, and successfully built mingw-w64-postgresql 16.1-1, with all necessary dependencies. Manjaro disappointed me, I was very used to it :(

**Comment by Martchus** [comment]
Don't be disappointed in Manjaro. It should be clear from the start that not all AUR packages are compatible with it. I'm closing this issue then because Manjaro is not supported by my packaging. If you have a Manjaro-specific patch you're nevertheless welcome to submit it as long as it doesn't make things worse under Arch.

**Comment by Martchus** [comment]
> Just now I specifically installed ArchLinux, built 'yay' and 'pamac', plugged in AUR, and successfully

Note that you might be able to follow https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot on Manjaro as this is basically just relying on a systemd-nspawn container. That's how official devs build packages (and how my binary repository is built). Of course you cannot use these packages under Manjaro directly (as you'd always needed to use an Arch container of some sort) but for mingw-w64 packages that may be acceptable.

By the way, it is even possible to use podman/docker as explained in https://github.com/Martchus/PKGBUILDs#container-image-building-packages-within-a-container. With this setup I sometimes build Arch packages under openSUSE and make use of them via an Arch container under openSUSE. So it is really not necessary to install Arch to use AUR packaging for the sake of cross-compilation.
