### ISSUE TITLE
Linker errors in `mingw-w64-freetype2`

### ISSUE THREAD

**Issue by FezzedOne** [Martchus/PKGBUILDs#174]
When I try to cross-compile my project and statically link it against your `mingw-w64-freetype2` package, I get linker errors like:

```
/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libfreetype.a(src_sfnt_sfnt.c.obj):(.text+0xec7e): undefined reference to `BrotliDecoderDecompress'
/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libfreetype.a(src_autofit_autofit.c.obj):(.text+0x2104): undefined reference to `hb_font_destroy'
/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libfreetype.a(src_autofit_autofit.c.obj):(.text+0x210d): undefined reference to `hb_buffer_destroy'
/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libfreetype.a(src_autofit_autofit.c.obj):(.text+0x21bc): undefined reference to `hb_blob_create'
```

... and so on, indicating that the linker can't find HarfBuzz or Brotli. I have all the required dependencies installed, my system is fully up to to date, and the linker's search directory is correctly set up as well. I even went as far as to explicitly specify HarfBuzz as a direct dependency of my project, but to no avail. Note that I have no such issues with native compilation on either Linux or Windows, just cross-compilation from Linux to Windows.

**Comment by Martchus** [comment]
You'll need to add the libraries harfbuzz and brotli to the linker line. Since freetype and harfbuzz are configured to support each other there's a cyclic dependency between them so on of the line needs to occur twice in the linker line. Not all build systems handle that well. I recommend using `mingw-w64-cmake-static` for CMake projects.

Maybe there's room for improvement here, e.g. when it comes to generating pkg-config files but that's most likely better done upstream.

**Comment by FezzedOne** [comment]
Thanks. I managed to get my cross-build working using `mingw-w64-freetype2-bootstrap`, since I don't need HarfBuzz. (Let's hope I don't get complaints from Chinese users...)

**Comment by Martchus** [comment]
I guess simply avoiding the complexity of the dependency cycle is a good idea as well. If this is about a Qt application then this is likely not affecting users because on Windows Qt uses Windows' built-in rendering by default anyways.

So I guess I can close the issue for now.
