### ISSUE TITLE
Update LuaJIT packages in ownstuff repository (binary)

### ISSUE THREAD

**Issue by hhromic** [Martchus/PKGBUILDs#178]
Hello!
The following binary packages in ownstuff should be REMOVED:
```
luajit-2.1
mingw-w64-luajit-2.1
```
The `luajit-2.1` package has been removed from the AUR and replaced by [`extra/luajit`](https://archlinux.org/packages/extra/x86_64/luajit/) which is more up-to-date.

The `mingw-w64-luajit-2.1` package has been removed from the AUR and should be replaced by [`mingw-w64-luajit`](https://aur.archlinux.org/packages/mingw-w64-luajit) which is also more-up-date and mirroring `extra/luajit` closely.

Given all the above, I would then like to request for the updated `mingw-w64-luajit` package to be ADDED to the ownstuff repository as a binary package. Afterwards, everything should be up-to-date and in order regarding LuaJIT in ownstuff.

Thanks a lot for your work and dedication, it is much appreciated!

EDIT: I requested the addition of the LuaJIT packages (and others) back then in 2019 in <https://github.com/Martchus/PKGBUILDs/issues/100> :).

**Comment by Martchus** [comment]
I removed the old packages and the new one is currently building.

**Comment by Martchus** [comment]
Looks like `mingw-w64-luajit-2.1.1713773202-1-x86_64.pkg.tar.zst` could be built.

**Comment by hhromic** [comment]
@Martchus Thanks a lot for the very quick reply and action!

I'm quite new at Arch Linux packaging. Do you think I should add `mingw-w64-luajit-2.1` to the list of packages that `mingw-w64-luajit` replaces/provides even though the former has been removed? Not sure how package disappearance is usually handled.

Also, I just noticed this morning that I forgot some very minor adjustments to the pkgconfig file in the new package. Therefore I will be pushing a pkgrel=2 soon that will require a rebuild of a new binary for it. Sorry about that! 🙈 

Apart from that the binary package works like a charm!

**Comment by Martchus** [comment]
I would only add replaces/provides if the new package is really a drop-in replacement. If it conflicts with the other package it would also make sense to add a conflict.

> Not sure how package disappearance is usually handled.

I think that's how it is handled covering the scope of users updating via pacman. When it comes to me updating the binary repo then this is rather manual. I sometimes go though the list of packages that no longer appear in the AUR and decide what to do with them (but not that often). So creating a ticket for this was the best option.

**Comment by hhromic** [comment]
> I would only add replaces/provides if the new package is really a drop-in replacement. If it conflicts with the other package it would also make sense to add a conflict.

Indeed the updated `mingw-w64-luajit` is a drop-in replacement.
It installs the exact same files as the removed `mingw-w64-luajit-2.1` package.
In fact I re-used most of the old package packaging logic for the new one.

However, I just tried installing the new one on a system where I still have the old one installed and seems that `pacman` is smart enough to detect the conflict itself (likely by installed files) and offer the replacement (neat!):
```
# pacman -S mingw-w64-luajit
resolving dependencies...
looking for conflicting packages...
:: mingw-w64-luajit-2.1.1713773202-1 and mingw-w64-luajit-2.1-2.1.0.beta3-3 are in conflict. Remove mingw-w64-luajit-2.1? [y/N] y

Package (2)                Old Version    New Version       Net Change  Download Size

mingw-w64-luajit-2.1       2.1.0.beta3-3                     -2.36 MiB
ownstuff/mingw-w64-luajit                 2.1.1713773202-1    2.60 MiB       0.62 MiB

Total Download Size:   0.62 MiB
Total Installed Size:  2.60 MiB
Net Upgrade Size:      0.24 MiB

:: Proceed with installation? [Y/n]
```

So looks like I don't have to explicitly add any replaces/provides and can keep it clean! 🎉 

As soon as I correct the pkgconfig file and push a new pkgrel, I will let you know here for a rebuild 🙏.
Thanks a lot for the help and advice, much appreciated.

**Comment by Martchus** [comment]
Looks like `mingw-w64-luajit` should have `arch=('any')` as it doesn't look like it would contain any binaries that are actually supposed to run on the build host (only binaries that are supposed to run on the target host).

**Comment by Martchus** [comment]
And it looks like pacman behaves that way because the *old* package has:

```
conflict = mingw-w64-luajit
provides = mingw-w64-luajit
```

This makes also most sense because usually conflicts/provides are added on the "variant" package (in this case the "variant" is `-2.1`, more common variants are `-git` and `-bin`).

**Comment by Martchus** [comment]
> After compiling LuaJIT, "minilua" is no longer needed.

And it also doesn't look like "minilua" is installed. So it does not become part of the final package. So the architecture should be `any` (even if the package doesn't build on *any* architecture; it is only relevant that the package can be used on any architecture).

**Comment by hhromic** [comment]
> > After compiling LuaJIT, "minilua" is no longer needed.
> 
> And it also doesn't look like "minilua" is installed. So it does not become part of the final package. So the architecture should be `any` (it is mainly relevant that the package can be used on any architecture).

Ah I see. Correct, the "minilua" interpreter is just thrown away after build and not installed/included.
Alright, will change archs to just be `any` then! 👍

**Comment by hhromic** [comment]
> Also, I just noticed this morning that I forgot some very minor adjustments to the pkgconfig file in the new package. Therefore I will be pushing a pkgrel=2 soon that will require a rebuild of a new binary for it. Sorry about that! 🙈

Alright, I just updated `mingw-w64-luajit` in the AUR with your feedback and fixed the pkgconfig file issue.

Can you rebuild and update the binary package at your earliest convenience?
Once again, thanks a lot for your help and maintaining this binary repository!
