### ISSUE TITLE
The mingw-w64-gcc package in the binary repository: libstdc++6.dll has no ios_base_library_init symbol

### ISSUE THREAD

**Issue by Lesya-cpp** [Martchus/PKGBUILDs#189]
Affected package (name and version): mingw-w64-gcc 13.1.0-1 and mingw-w64-qt6-declarative 6.7.2-1
Used mirror: https://ftp.f3l.de/~martchus/

Brief description of the problem:
I'm trying to cross compile a Qt6 program from Arch Linux to Win64 with mingw-w64 using cmake.
After successfully building and linking the code I try to run the program on Windows 11. I get "The procedure entry point _ZSt21ios_base_library_initv could not be located in the dynamic link library QtQml6.dll".
The symbol is the part of standard c++ library; also the Dependencies Gui shows the symbol is supposed to be in libstdc++-6.dll.
Is QtQml6.dll built against the other version of libstdc++.dll than the one in the binary repo?
The strange thing is that the program starts with wine..

**Comment by Martchus** [comment]
The package probably needs to be rebuild against mingw-w64 after updating it to version 12. I triggered a rebuild.

**Comment by Martchus** [comment]
The dynamic version of the package has just been rebuilt. So you can try updating and check whether it helped.

**Comment by Lesya-cpp** [comment]
Thanks. Now It's working ☺️

**Comment by Martchus** [comment]
Great, then I'm closing this issue.
