### ISSUE TITLE
undefined reference to `__imp___p___argc' [mingw-w64-qt6-base]

### ISSUE THREAD

**Issue by hipersayanX** [Martchus/PKGBUILDs#191]
Affected package (name and version): mingw-w64-qt6-base 6.7.2-1.1
Used mirror: ftp.f3l.de

When linking the executable, it can't find ```__imp___p___argc```.

```
/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libQt6EntryPoint.a(qtentrypoint_win.cpp.obj):(.text+0xc0): undefined reference to `__imp___p___argc'
```

**Comment by Martchus** [comment]
Are you using mingw-w64-crt from my repo? You cannot use the package from the official repo. The same counts for mingw-w64-gcc.

**Comment by hipersayanX** [comment]
[Yes](https://github.com/webcamoid/webcamoid/blob/2ade92f7a0dd0b14cba6db5bcef998d0d6fab6f2/ports/ci/linux-mingw/install_deps.sh#L35), or I think so. I have been [using it](https://github.com/webcamoid/webcamoid/actions/workflows/linux-mingw.yml) until last month and had not any problem, today I checked and it was failing with that message.
Something changed between [2024-07-09](https://github.com/webcamoid/webcamoid/actions/runs/9865314607) and [2024-07-30](https://github.com/webcamoid/webcamoid/actions/runs/10168704423), and I did not touched any code related to Windows in my side.

**Comment by Martchus** [comment]
This script looks as it would prefer packages from official repos over mine which won't work and lead to errors like the one you've got.

**Comment by hipersayanX** [comment]
It must go before core?

**Comment by Martchus** [comment]
It must go before wherever official mingw-w64 packages live - I think this is extra.

**Comment by Martchus** [comment]
Because I updated mingw-w64 and GCC.

**Comment by hipersayanX** [comment]
And it was the case, fixed. Thanks a lot!
