### ISSUE TITLE
Why, for example, mingw-w64-ffmpeg is not granted for download? HTTP 403 error

### ISSUE THREAD

**Issue by DX37** [Martchus/PKGBUILDs#22]
Question is in title.

**Comment by DX37** [comment]
Is it because of `:` symbol in package name? It's `mingw-w64-ffmpeg-1:3.2.4-1-any.pkg.tar.xz`.

**Comment by Martchus** [comment]
I restricted access intentionally. The ffmpeg in my repository links against libfdk_aac. This is actually the reason for me to build ffmpeg myself so I won't change it.

Currently the following regex is used to deny public access for certain packages:
```
(.*ffmpeg.*|.*-w64-.*-all.*|.*nero.*|.*acro.*|.*fdkaac.*|.*oracle.*|.*jre.*|.*jdk.*¦.*spotify.*|.*masterpdfeditor.*|.*skypeforlinux.*)
```

Maybe I automate building in the future. Then I can add more variants without having too much effort.

**Comment by Martchus** [comment]
Seems like the 403 error prevents updating when the blocked package is installed from the AUR. I'll have to split the repository.

**Comment by Martchus** [comment]
The packages I'm not permitted to distribute are now in a separate repository so there shouldn't be any problems when having any of it installed from the AUR. Also, the restriction is now not confusing anymore.
