### ISSUE TITLE
gogs 0.11.4: cannot updload custom avatars

### ISSUE THREAD

**Issue by hrimfaxi** [Martchus/PKGBUILDs#25]
gogs UploadAvatar: Create: open /usr/bin/data/avatars/1: no such file or directory

Could be something wrong with new binary location as /usr/bin/gogs instead of /usr/share/gogs?

**Comment by Martchus** [comment]
Avatars should definitely go to some place under `/var/lib/gogs`. I'll check whether this is configurable and change the default config then.

**Comment by Martchus** [comment]
Ok, it is just a setting. I'll change the default path for avatars to `/var/lib/gogs/avatars` where Gogs will be able to write. So far, you can just update your `/etc/gogs/app.ini` manually. See https://github.com/Martchus/gogs/commit/866c5d2cafa1d2a0914532e1d738678f7061952a#diff-c4893a32340ee2cee87e664d67f8abf3R283.

**Comment by Martchus** [comment]
I'm closing, feel free to reopen if something is missing.
