### ISSUE TITLE
mingw-w64-qt5-declarative 5.7.0, missing library linking and wrong strip

### ISSUE THREAD

**Issue by hipersayanX** [Martchus/PKGBUILDs#3]
Hi. Package build ends with:

    rm -f libQt5QmlDevTools.so.5.7.0 libQt5QmlDevTools.so libQt5QmlDevTools.so.5 libQt5QmlDevTools.so.5.7
    g++ -Wl,--no-undefined -Wl,--version-script,QtQmlDevTools.version -shared -Wl,-Bsymbolic-functions -Wl,-soname,libQt5QmlDevTools.so.5 -o libQt5QmlDevTools.so.5.7.0 .obj/qqmljsast.o .obj/qqmljsastvisitor.o .obj/qqmljsengine_p.o .obj/qqmljsgrammar.o .obj/qqmljslexer.o .obj/qqmljsparser.o .obj/qv4runtime.o .obj/qv4string.o .obj/qv4value.o .obj/qv4compileddata.o .obj/qv4compiler.o .obj/qv4codegen.o .obj/qv4isel_p.o .obj/qv4jsir.o .obj/qv4ssa.o .obj/qqmlirbuilder.o  -L/usr/lib -L/usr/i686-w64-mingw32/lib -lQt5Bootstrap -lpthread  
    /usr/lib/libQt5Bootstrap.a(qbytearray.o): In function `qUncompress(unsigned char const*, int)':
    (.text._Z11qUncompressPKhi+0xa3): undefined reference to `uncompress'
    /usr/lib/libQt5Bootstrap.a(qbytearray.o): In function `qCompress(unsigned char const*, int, int)':
    (.text._Z9qCompressPKhii+0xcc): undefined reference to `compress2'
    collect2: error: ld returned 1 exit status

When you patched the module for shared build, you forgot to link with **zlib**.
<hr/>
In [PKGBUILD at L63](https://github.com/Martchus/PKGBUILDs/blob/master/qt5-declarative/mingw-w64/PKGBUILD#L63), the line:

    strip --strip-unneeded "${pkgdir}/usr/${_arch}/lib/"*.so.$pkgver

must be:

    ${_arch}-strip --strip-unneeded "${pkgdir}/usr/${_arch}/lib/"*.a

because you are stripping a Windows binary, and you will probably need to strip the DLL files too:

    ${_arch}-strip --strip-unneeded "${pkgdir}/usr/${_arch}/bin/"*.dll

**Comment by Martchus** [comment]
I was able to build it last time I tried it, but I'm looking into it. The linker flag for zlib might be missing indeed.

However, the mentioned patch should ensure that the file `"${pkgdir}/usr/${_arch}/lib/"*.so.$pkgver` is created and not `"${pkgdir}/usr/${_arch}/lib/"*.a`. Hence I'm using this path. This library is a native one, so it is correct to use the native strip command. `The same counts for "${pkgdir}/usr/${_arch}/lib/qt/bin/"*`.

Libs (both DLLs and import libs) should be already stripped with the `find "${pkgdir}/usr/${_arch}" -name "*.a" -o -name "*.dll" | xargs -rtl1 ${_arch}-strip -g` command.

**Comment by hipersayanX** [comment]
> Additionally, there should be no /usr/lib/libQt5Bootstrap.a as your error message states. This static library is no part of the mingw-w64-qt5-base package I provide. However, mingw-w64-qt5-declarative is intended to be used with that particular mingw-w64-qt5-base package which provides the shared libraries /usr/{i686,x86_64}-w64-mingw32/lib/libQt5Bootstrap.so instead.

You're right, libQt5Bootstrap.a was compiled because i've disabled the patches, so ignore the stripping error. Thanks a lot for your work :smiley:

**Comment by Martchus** [comment]
Did you also ignore patches when building mingw-w64-qt5-base? This could be the reason why your mingw-w64-qt5-base is differs.

I know all those patches are a pain, but unfortunately most of them are still required to package Qt appropriately for cross compilation and to avoid conflicts with mingw-w64-qt4.

**Comment by hipersayanX** [comment]
Nope, I did compiled mingw-w64-qt5-base without any problems, i also compiled quickcontrols and quickcontrols2, and now i'll try with script, svg and tools. If any problem i will advice you.

**Comment by Martchus** [comment]
Ok, so I assume this issue can be closed.
