### ISSUE TITLE
Lack of qt gif plugin

### ISSUE THREAD

**Issue by ohmyarch** [Martchus/PKGBUILDs#4]
when i try to compile a qt library, errors occurred:
CMake Error at /usr/i686-w64-mingw32/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:15 (message):
  The imported target "Qt5::Gui" references the file

     "/usr/i686-w64-mingw32/lib/qt/plugins/imageformats/qgif.dll"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/i686-w64-mingw32/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/i686-w64-mingw32/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:179 (_qt5_Gui_check_file_exists)
  /usr/i686-w64-mingw32/lib/cmake/Qt5Gui/Qt5Gui_QGifPlugin.cmake:4 (_populate_Gui_plugin_properties)
  /usr/i686-w64-mingw32/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:196 (include)
  /usr/i686-w64-mingw32/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:98 (find_package)
  /usr/i686-w64-mingw32/lib/cmake/Qt5/Qt5Config.cmake:26 (find_package)
  CMakeLists.txt:29 (find_package)

**Comment by Martchus** [comment]
This error looks familiar, but I belief I already fixed it.

Please provide more information about what you're actually doing.
Are you trying to link dynamically or statically?
Are you using
1. the PKBUILD from the AUR? It has not been updated yet and hence issues concerning the static version have not been fixed yet. (Pending merge request is blocking.)
2. the package from my binary repository? I updated the packages mingw-w64-qt5-\*-5.7.0-4-x86_64.pkg.tar.xz a few times without increasing pkgrel so you might still use an incorrect version. (I know not increasing pkgrel is bad practise. I haven't thought that anybody is *actually* using my binary repo so I didn't care.)
3. the PKGBUILD from this GitHub repo? I think the issue should have been fixed yet but I'm obviously wrong. In this case, please provide steps to reproduce (eg. minimal CMake project file).

**Comment by ohmyarch** [comment]
@Martchus I'm using your binary repository, it's awesome. I just reinstall the package mingw-w64-qt5-base, then the problem was fixed. 😄

**Comment by Martchus** [comment]
Good to hear. Next time I'll increase the pkgrel and use a separate repo for testing experimental packages.
