### ISSUE TITLE
Update mingw-w64-gcc to 7.2.1+20171224

### ISSUE THREAD

**Issue by ohmyarch** [Martchus/PKGBUILDs#49]

**Comment by Martchus** [comment]
I assume this is about the binary repository as the package is actually not maintained by me.
The repository has been updated: https://martchus.no-ip.biz/repo/arch/ownstuff/os/x86_64/mingw-w64-gcc-7.2.1+20171224-1-x86_64.pkg.tar.xz

Note that I regularly check for updates so in general it is not required to create an issue for this. Sometimes it just takes a few days till I have time to build new packages. However, if you think I missed something, you can create an issue of course.
