### ISSUE TITLE
Patch fail in mingw-w64-qt5-base

### ISSUE THREAD

**Issue by markand** [Martchus/PKGBUILDs#5]
Hello,

I was trying to build mingw-w64-qt5-base but one patch failed:

````
==> Validating source files with md5sums...
    qtbase-opensource-src-5.7.0.tar.xz ... Passed
    qt5-add-angle-support.patch ... Passed
    qt5-use-external-angle-library.patch ... Passed
    qt5-workaround-pkgconfig-install-issue.patch ... Passed
    qt5-merge-static-and-shared-library-trees.patch ... FAILED
    qt5-fix-linking-against-static-pcre.patch ... Passed
    qt5-rename-qtmain-to-qt5main.patch ... Passed
    qt5-dont-build-host-libs-static.patch ... Passed
    qt5-enable-rpath-for-host-tools.patch ... Passed
    qt5-dont-add-resource-files-to-qmake-libs.patch ... Passed
    qt5-prevent-debug-library-names-in-pkgconfig-files.patch ... Passed
    qt5-fix-linking-against-static-dbus.patch ... Passed
    qt5-use-win32-g++-mkspecs-profile.patch ... Passed
    qt5-use-system-zlib-in-host-libs.patch ... Passed
    qt5-fix-opengl-to-many-sections.patch ... Passed
    qt5-fix-static-psql-mysql.patch ... Passed
    qt5-fixes-from-mxe.patch ... Passed
    qt5-fix-implib-ext.patch ... Passed
    qt5-disable-default-lib-include-detection.patch ... Passed
    qt5-win32-static-cmake-link-ws2_32-and--static.patch ... Passed
    qt5-allow-usage-of-static-qt-with-cmake.patch ... Passed
    qt5-customize-extensions-for-static-build.patch ... Passed
    qt5-use-correct-pkg-config-static-flags.patch ... Passed
    qt5-use-pkgconfig-for-harfbuzz.patch ... Passed
==> ERROR: One or more files did not pass the validity check!
````

I will try to update the md5sums to test.

**Comment by markand** [comment]
After changing it, it now fails later:

````
make[2]: Leaving directory '/home/markand/AUR/mingw-w64-qt5-base/src/build-i686-w64-mingw32/src/tools/rcc'
cd 3rdparty/pcre/ && ( test -e Makefile || /home/markand/AUR/mingw-w64-qt5-base/src/build-i686-w64-mingw32/bin/qmake /home/markand/AUR/mingw-w64-qt5-base/src/qtbase-opensource-src-5.7.0/src/3rdparty/pcre/pcre.pro -qtconf /home/markand/AUR/mingw-w64-qt5-base/src/build-i686-w64-mingw32/bin/qt.conf -o Makefile ) && make -f Makefile 
Cannot find file: /home/markand/AUR/mingw-w64-qt5-base/src/qtbase-opensource-src-5.7.0/src/3rdparty/pcre/pcre.pro.
make[1]: *** [Makefile:164: sub-3rdparty-pcre-make_first] Error 2
make[1]: Leaving directory '/home/markand/AUR/mingw-w64-qt5-base/src/build-i686-w64-mingw32/src'
make: *** [Makefile:42: sub-src-make_first] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
markand@melon [git mingw-w64-qt5-base] (master) $ 
markand@melon [git mingw-w64-qt5-base] (master) $ find . -name pcre.pro
find: ‘./pkg’: Permission denied
./src/qtbase-opensource-src-5.7.0/config.tests/unix/pcre/pcre.pro
````

**Comment by Martchus** [comment]
I will fixed the messed hashes, but I'm not sure about the other error. I want to rebuild the packages anyways to check whether the dynamic switch (for OpenGL backend) works. Maybe I can reproduce the error then. I see you're building in your home directory.

The project file which could not be found is removed in the PKGBUILD to use pcre provided by mingw-w64-pcre package instead of the bundled version. For me this works (at least it worked last time I tried to build the package), but you could try adding `-system-pcre` flag to explicitly specify usage system pcre.

**Comment by Martchus** [comment]
You could try to build the version from qt5-dynamic-opengl branch. One of the hashes was wrong, indeed. I also added the mentioned flag to be sure system pcre is used. I'm currently trying to build it so let's wait whether I can reproduce the error.

When this link becomes valid you'll know the build succeeded for me: https://martchus.no-ip.biz/repo/arch/ownstuff/os/x86_64/mingw-w64-qt5-base-5.7.0-5-x86_64.pkg.tar.xz

**Comment by markand** [comment]
I think you have mingw-w64-pcre installed because it built once installed. I think you have it installed from an other dependency because this package does not depend directly on mingw-w64-pcre. Would you mind adding this depend please? :)

I have removed the postgresql/mysql connectors from the PKGBUILD, I think the pcre depend should come from them.

**Comment by Martchus** [comment]
pcre comes from glib2 and hence should be installed. Adding dependencies already pulled by other dependencies should be avoided I think but I can add it though.

BTW: The version from qt5-dynamic-opengl branch needs further fixing, just in case you tried to build it.

So installing mingw-w64-pcre solves the issue?

**Comment by markand** [comment]
> BTW: The version from qt5-dynamic-opengl branch needs further fixing, just in case you tried to build it.

I've just tried the one from the AUR with postgresql/mysql removed.

> So installing mingw-w64-pcre solves the issue?

Yes :)

**Comment by Martchus** [comment]
I've added mingw-w64-pcre explicitly and fixed the checksum so I guess this is resolved.

**Comment by markand** [comment]
Thanks!

**Comment by markand** [comment]
Thanks!
