### ISSUE TITLE
include mingw-w64-lapack

### ISSUE THREAD

**Issue by xantares** [Martchus/PKGBUILDs#50]
would it be possible to include mingw-w64-lapack on your ownstuff binary repo ?

**Comment by Martchus** [comment]
Added: https://martchus.no-ip.biz/repo/arch/ownstuff/os/x86_64/mingw-w64-lapack-3.8.0-1-any.pkg.tar.xz

**Comment by xantares** [comment]
thanks! that will save me some build time
