### ISSUE TITLE
Sign binary packages

### ISSUE THREAD

**Issue by Martchus** [Martchus/PKGBUILDs#51]
Since the binary repo seems to be actually used by other people, it might make sense to finally look into package signing.

**Comment by yan12125** [comment]
Seems this is already fixed? There is a relevant issue at https://github.com/Martchus/PKGBUILDs/issues/131, and the Arch wiki page is updated https://wiki.archlinux.org/index.php?title=Unofficial_user_repositories&type=revision&diff=655209&oldid=654260. Both happened on 17 March 2021 :)

**Comment by Martchus** [comment]
True, I've totally forgotten that I've actually created an issue for this.
