### ISSUE TITLE
can add nginx_substitutions_filter module to nginx/custom ?

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [Martchus/PKGBUILDs#64]
can add this module to nginx/custom ?

follow is the module pages.
https://www.nginx.com/resources/wiki/modules/substitutions/

and it add regex support to ngx_http_sub_module when use sub_filter directive.

**Comment by Martchus** [comment]
I created a separate package for that module which is now available in this Git repo and in my binary repo.

Since the last release was years ago, I picked a newer commit. Let me know if it works.

**Comment by Martchus** [comment]
Just reopen if something is missing or not working.
