### ISSUE TITLE
Add mingw-w64-paraview

### ISSUE THREAD

**Issue by xantares** [Martchus/PKGBUILDs#66]
Also I was wondering, would you mind adding mingw-w64-paraview to your binary repo ?
This one takes quite some time to build for me (only 2 cores here :) and needs a few dependencies that are not yet on your repo:
- mingw-w64-jsoncpp
- mingw-w64-pugixml
- mingw-w64-lz4
- mingw-w64-cgns
- mingw-w64-netcdf-cxx-legacy
- mingw-w64-eigen

**Comment by Martchus** [comment]
Ok, why not. At this point (202 mingw-w64 packges) a few more don't make difference anymore.

But providing you a way to upload would really make sense. Maybe just a simple scripts which allows to upload via curl. Those packages could land directly in my staging.

**Comment by xantares** [comment]
Yes, why not. I know the scp command, it needs a user, a password and a location to copy, eg `scp mingw-paraview.xz -P 8022 xantares@martchus.no-ip.biz:/mnt/repo/arch/ownstuff-staging/os/x86_64/`

**Comment by Martchus** [comment]
Seems like the paraview package should have wine as make dependency:
```
/usr/bin/i686-w64-mingw32-wine: line 25: wine: command not found
```

**Comment by xantares** [comment]
Yes, totally it generates some wrapper code.
I'll add it, thanks.

**Comment by xantares** [comment]
Added

**Comment by Martchus** [comment]
Packaged added, too. "Only" 90 MiB :-)
