### ISSUE TITLE
Rebuild fortran packages

### ISSUE THREAD

**Issue by xantares** [Martchus/PKGBUILDs#69]
gcc8 bumped libgfortran soversion, so fortran packages must be rebuilt.
I bumped mingw-w64-lapack, but it didnt show up on your repo.
dependent packages (hdf5, netcdf ...) will also need to be rebuilt.

**Comment by Martchus** [comment]
Usually I check for required rebuilds myself and keep packages in staging till everything has been rebuilt. But this one slipped through. Haven't expected that something in the repo actually used that library (that's the problem if you add packages you're not familiar with).

According to `xzgrep -i libgfortran-4.dll mingw-w64-*.pkg.tar.xz` only the following packages are referencing the  concerned:
```
mingw-w64-blas-3.8.0-1-any.pkg.tar.xz
mingw-w64-lapack-3.8.0-1-any.pkg.tar.xz
```

Why do you think dependend packages will also need to be rebuilt? This is usually not the case as long as those don't reference the library directly, too.

**Comment by xantares** [comment]
I thought so, but you're probably right then. Less packages to rebuild then :)

**Comment by Martchus** [comment]
Done
