### ISSUE TITLE
Must construct a QCoreApplication before QJSEngine (mingw-w64-qt5-base-dynamic 5.11.0)

### ISSUE THREAD

**Issue by hipersayanX** [Martchus/PKGBUILDs#70]
Compiling this code in Debug mode:

```
#include <QCoreApplication>
#include <QQmlApplicationEngine>
#include <QtDebug>

int main(int argc, char *argv[])
{
    QCoreApplication app(argc, argv);
    QJSEngine engine; // Crash here

    return app.exec();
}
```

and running in wine (did not tried in Windows) gives this error message and crash:

>QJSEngine: Must construct a QCoreApplication before QJSEngine

tested in both x86_64 and i686. It works ok in Release mode.

**Comment by Martchus** [comment]
Not nice, I'm also using this in my own projects tag editor and syncthingctl. Let's see whether it goes away when updating to 5.11.1 (PGKBUILDs already updated on update-mingw64-qt5 branch, just need to rebuild).

**Comment by Martchus** [comment]
If haven't looked into this yet, but updated the mingw-w64 packages to 5.11.1. Maybe the issue is already solved by that. Could you also reproduce this under Windows (and not only Wine)?

**Comment by hipersayanX** [comment]
Ok, will update the system and will tell you if it worked.

**Comment by hipersayanX** [comment]
Working again :+1:
