### ISSUE TITLE
Update pocketsphinx for python 3.7

### ISSUE THREAD

**Issue by xantares** [Martchus/PKGBUILDs#72]
Just change 3.6 to 3.7 in the PKGBUILD, or better remove these libtool commands as I dont think they are useful.

Cannot issue a pr here as it was edited by comaintainer, must be synced first.

**Comment by Martchus** [comment]
I updated sphinxbase and pocketsphinx here (completely removed the libtool commands). In the AUR I have only write access to pocketsphinx so far.

BTW, you can also submit a PR containing the sync plus your modifications. I'm only doing this manually, too (and only before I want to push a change).
