### ISSUE TITLE
Help missing signature 

### ISSUE THREAD

**Issue by toufikbelouadah** [Martchus/PKGBUILDs#76]
~ pacman -S mingw-w64-gcc
resolving dependencies...
looking for conflicting packages...

Package (5)                           New Version  Net Change

ownstuff/mingw-w64-binutils-symlinks  2.31.1-1      45.72 MiB
ownstuff/mingw-w64-crt                6.0.0-1      135.08 MiB
ownstuff/mingw-w64-headers            6.0.0-1      115.41 MiB
ownstuff/mingw-w64-winpthreads        6.0.0-1        1.92 MiB
ownstuff/mingw-w64-gcc                8.2.0-1      710.91 MiB

Total Installed Size:  1009.04 MiB

:: Proceed with installation? [Y/n] 
(5/5) checking keys in keyring                                                             [#####################################################] 100%
(5/5) checking package integrity                                                           [#####################################################] 100%
error: mingw-w64-crt: missing required signature
error: mingw-w64-binutils-symlinks: missing required signature
error: mingw-w64-winpthreads: missing required signature
error: mingw-w64-headers: missing required signature
error: mingw-w64-gcc: missing required signature
error: failed to commit transaction (package missing required signature)
Errors occurred, no packages were upgraded.

**Comment by Martchus** [comment]
How looks your `/etc/pacman.conf`? That the packages aren't signed is [a known issue](https://github.com/Martchus/PKGBUILDs/issues/51) so you need to allow that.

When I will improve the overall workflow of my builds I'm going to take signing into account. That just has not happened yet.

**Comment by toufikbelouadah** [comment]
at first i thought u had some kind of gpg key that u signed ur packages with and i screwed it up
but it turns out i had to ignore signing in pacman conf

[ownstuff]
Server = http://martchus.no-ip.biz/repo/arch/$repo/os/$arch

i added
SigLevel = Never 

and it worked.  is it fine ? if yes you can close this 

and Thank you so mush for maintaining cross compilation binaries ^^

**Comment by Martchus** [comment]
Glad I could help :-)
