### ISSUE TITLE
gitea: package changed a lot, must be updated

### ISSUE THREAD

**Issue by mckaygerhard** [Martchus/PKGBUILDs#82]
as you now i'm packaging gitea 1.5.3 and 1.6.X and got some problems and some updates.. 

* default config files are gone and there's only custom file (present or not)
* default orignal files are in root working dir and customs of them are under conf directory, that are not documented in gitea in any place (i opened a issue agains documentation and build process in upstream)
   * by example, the template files for README, igtignore and LICENSES are detecte under "`APP_WORKING_DIR/conf`" but if you can distribute also default non-customized can put origial files in "`APP_WORING_DIR`"; well really must be in `APP_STATIC_DIR`, but there's a bug when gitea doesn't honr those directories.
   * so then if user or admin os wants to customized some of these, only must put or have a copy into the `APP_WORKING_DIR/conf` directory and that's all..
* compilation process in gitea have the "bindata" tag, that build everithing buld-in, in the binary, in that case, the `APP_STATIC_DIR` are ignored and only applied the `APP_WORING_DIR`.. (and that's why theres a bug about that tyhose dirs are not honerd), i prefers not to build a bindata package due in that case works similar to gogs package (ecxept for the abstent of the ini default file, in gitea now only are a `APP_WORING_DIR/custom/conf/app.ini` and the default values are build-in in code)

many of those tips and documented things i not still shared at upstream due the projectr developers have a poor behaviour respect document property the things.. and have a unconsistent prority level about importnat of roadmap tarjets

**Comment by Martchus** [comment]
There's already an official package for gitea. The one provided in this repo can be considered obsolete and I'm not taking any effort to update it anymore.

Or are you saying your one of the maintainer listed on https://www.archlinux.org/packages/community/x86_64/gitea ("as you now i'm packaging gitea 1.5.3 and 1.6.X")? What is the purpose the this issue then?

**Comment by mckaygerhard** [comment]
was ony a colaborative issue for you, but if you said gitea has a official package i ssumed are from distro, the pacakge from gitea pcakgin service its just a binary generic build with workarounds scripts..

thanks for your answer. i'll close then and reopen if you need some info.
