### ISSUE TITLE
mingw-w64-freetype2-bootstrap fails to build

### ISSUE THREAD

**Issue by z3ntu** [Martchus/PKGBUILDs#84]
```
/usr/lib/gcc/i686-w64-mingw32/8.2.0/../../../../i686-w64-mingw32/bin/ld: /build/mingw-w64-freetype2-bootstrap/src/freetype-2.9.1/build-i686-w64-mingw32/.libs/psnames.o:psnames.c:(.text+0x641): undefined reference to `__stack_chk_guard'
/usr/lib/gcc/i686-w64-mingw32/8.2.0/../../../../i686-w64-mingw32/bin/ld: /build/mingw-w64-freetype2-bootstrap/src/freetype-2.9.1/build-i686-w64-mingw32/.libs/psnames.o:psnames.c:(.text+0x774): undefined reference to `__stack_chk_fail'
```
All AUR dependencies were freshly built.

**Comment by Martchus** [comment]
Maybe this happens because of https://aur.archlinux.org/cgit/aur.git/commit/?h=mingw-w64-configure&id=bafe467b43d3b0a90bda14d08d212cd9d177310b .

**Comment by z3ntu** [comment]
Yep, reverting that commit makes mingw-w64-freetype2-bootstrap build!

**Comment by Martchus** [comment]
I haven't had time to investigate myself. Maybe `-fstack-protector-strong` needs to be on the linker line, too (`default_mingw_linker_flags` variable in the configure wrapper).

**Comment by Martchus** [comment]
I've reverted the change to use `-fstack-protector-strong` in the CMake package for now.
