### ISSUE TITLE
Checksum failure in mingw-w64-qt5-tools-5.7.0-2-x86_64.pkg.tar.xz

### ISSUE THREAD

**Issue by kuldeepdhaka** [Martchus/PKGBUILDs#9]
Twice downloaded over https:
MD5SUM
0f3202768121ac88f7413aff053fc4b6  mingw-w64-qt5-tools-5.7.0-2-x86_64.pkg.tar.xz
SHA256SUM
c3d2179c7e6b69bb1fccfeef15d04c32df5ec269e92a0b508b2ce3c1516a39ff  mingw-w64-qt5-tools-5.7.0-2-x86_64.pkg.tar.xz

BUT,
desc file report:
%MD5SUM%
a0e46930aa3ffdfa47724bc1387219c9

%SHA256SUM%
5fa79d536bfdad92a4896d5412571d4a3a788fecfbbdd920ba797133c48d95c3

which result in 
":: File /var/cache/pacman/pkg/mingw-w64-qt5-tools-5.7.0-2-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (checksum))."

**Comment by kuldeepdhaka** [comment]
Source: https://martchus.no-ip.biz/repo/arch/ownstuff/os/x86_64/

**Comment by Martchus** [comment]
Should be fixed now. But I'll rebuild soon anyway (when 5.7.1 is out).
