### ISSUE TITLE
[qt5-*] Wrong sha256 checksums

### ISSUE THREAD

**Issue by teohhanhui** [Martchus/PKGBUILDs#93]
I don't know what happened, but the sha256 checksums for the qt5 submodules are clearly wrong, compared to the official sources (sha256 checksum for each file can be found by clicking "Details"):

https://download.qt.io/official_releases/qt/5.12/5.12.3/submodules/

Without looking at the update scripts, I'm guessing you're using the checksums published elsewhere, and they've messed up there.

**Comment by teohhanhui** [comment]
If you don't get to it before me, I'll send a PR fixing all the checksums later.

**Comment by Martchus** [comment]
Seems like I've simply forgotten to update the checksums, e.g. https://aur.archlinux.org/cgit/aur.git/commit/?h=mingw-w64-qt5-declarative&id=4919f3244e17b16b3987f20d07512a9ffe783218 shows that only the patch checksums have been updated. I'm going to fix this as it only requires invoking one script for me (which I have apparently forgotten to do).

**Comment by teohhanhui** [comment]
If you're open to having a CI build that will catch these basic errors next time, I'll see what I can do.

**Comment by Martchus** [comment]
It seems like the changes are actually in this PKGBUILDs repo and just not in the AUR. Likely I've ran the script to transfer packages from here to the AUR too early.

**Comment by teohhanhui** [comment]
I've checked and the sha256 checksums in the repo are wrong too. Even though they've been updated.

**Comment by teohhanhui** [comment]
Uhh, the ones published on the Qt download site are wrong. Sorry...
